### ISSUE TITLE
Bug: Starting minecraft server crashes due to LCT predicates

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/MineLabs#173]
Trace:
```
[22:47:53] [main/FATAL] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'scicraft'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.9.jar:?]
	at net.minecraft.server.Main.main(Main.java:107) [minecraft-project-@-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.minecraft.client.item.UnclampedModelPredicateProvider in environment type SERVER
	at be.uantwerpen.scicraft.item.Items.registerAtom(Items.java:204) ~[main/:?]
	at be.uantwerpen.scicraft.item.Items.<clinit>(Items.java:137) ~[main/:?]
	at be.uantwerpen.scicraft.Scicraft.onInitialize(Scicraft.java:28) ~[main/:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.minecraft.client.item.UnclampedModelPredicateProvider in environment type SERVER

	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.9.jar:?]
	... 11 more
Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.item.UnclampedModelPredicateProvider in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:264) ~[fabric-loader-0.12.9.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.item.UnclampedModelPredicateProvider in environment type SERVER

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at be.uantwerpen.scicraft.item.Items.registerAtom(Items.java:204) ~[main/:?]
	at be.uantwerpen.scicraft.item.Items.<clinit>(Items.java:137) ~[main/:?]
	at be.uantwerpen.scicraft.Scicraft.onInitialize(Scicraft.java:28) ~[main/:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.9.jar:?]
	... 11 more
```

**Comment by JorenFa** [comment]
Fixed in 0fbcb32
