### ISSUE TITLE
Coulomb: Load data of ChargedEntity as Resource

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#784]
Should resolve issue with saving to NBT

```
[20:08:48] [Server thread/WARN] (Minecraft) Exception loading entity: 
 net.minecraft.util.crash.CrashException: Loading entity NBT
	at net.minecraft.entity.Entity.readNbt(Entity.java:1826) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.entity.EntityType.method_17839(EntityType.java:549) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.Util.ifPresentOrElse(Util.java:512) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.entity.EntityType.getEntityFromNbt(EntityType.java:548) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.entity.EntityType.loadEntityFromNbt(EntityType.java:635) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.entity.EntityType.loadEntityWithPassengers(EntityType.java:586) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.entity.EntityType$1.method_31490(EntityType.java:609) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at net.minecraft.entity.EntityType$1.tryAdvance(EntityType.java:608) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.storage.EntityChunkDataAccess.method_31731(EntityChunkDataAccess.java:76) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor.java:91) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor.java:146) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor.java:102) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:786) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:165) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:768) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:762) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:746) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:679) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:168) ~[?:?]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:76) ~[?:?]
	at be.minelabs.entity.ChargedEntity.loadData(ChargedEntity.java:97) ~[main/:?]
	at be.minelabs.entity.ChargedEntity.readCustomDataFromNbt(ChargedEntity.java:274) ~[main/:?]
	at net.minecraft.entity.Entity.readNbt(Entity.java:1817) ~[minecraft-common-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	... 33 more
```

**Comment by pixar02** [comment]
@JoeyDP Could you check if this is the way it's supposed to be?
